accelerate launch --config_file /data7/sooyeon/LyCORIS/gpu_config/gpu_6_7_config --main_process_port 26724 training_contrastive.py \
  --logging_dir ../result/logs --process_title parksooyeon --max_token_length 225 \
  --log_with wandb --log_with wandb --wandb_api_key 3a3bc2f629692fa154b9274a5bbe5881d47245dc \
  --wandb_init_name 'bagel_training' --wandb_run_name 1_contrastive_learning_eps_0.0 \
  --seed 42 --output_dir ../result/MVTec_experiment/bagel/1_contrastive_learning_eps_0.0 \
  --pretrained_model_name_or_path /data7/sooyeon/pretrained_stable_diffusion/stable-diffusion-v1-5/v1-5-pruned.safetensors \
  --network_module networks.lora --network_dim 64 --network_alpha 4 --train_batch_size 2 \
  --optimizer_type AdamW --lr_scheduler cosine_with_restarts --lr_warmup_steps 144 \
  --learning_rate 0.0003 --unet_lr 0.0001 --text_encoder_lr 0.00005 --resolution 512,512 \
  --save_every_n_epochs 1 --sample_every_n_epochs 1 --sample_prompts /data7/sooyeon/MyData/object/bagel_inference.txt \
  --max_train_steps 48000 --train_data_dir /data7/sooyeon/MyData/anomaly_detection/MVTecAD/paired_data/bad \
  --resolution 512,512 --class_caption 'good' --sample_prompts /data7/sooyeon/MyData/object/bagel_inference.txt --contrastive_eps 0.0